name: PR Label Checker

on:
  pull_request:
    branches: 
    - master
    types: [ labeled, opened, unlabeled ]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for labels (feature, config-changes, rollout,  bugfix, hotfix, non-functional)
      if: >
        contains(github.event.pull_request.labels.*.name, 'feature') == false &&  
        contains(github.event.pull_request.labels.*.name, 'config-changes') == false && 
        contains(github.event.pull_request.labels.*.name, 'rollout') == false &&
        contains(github.event.pull_request.labels.*.name, 'bugfix') == false &&
        contains(github.event.pull_request.labels.*.name, 'hotfix') == false && 
        contains(github.event.pull_request.labels.*.name, 'non-functional') == false 
      run: |
        echo "Error: PR must have one of the following labels: feature, config-changes, rollout, bugfix, hotfix, non-functional"
        exit 1
